/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task.manager12;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author karthik
 */
public class main_frame12 extends javax.swing.JFrame {

    /**
     * Creates new form main_frame12
     */
    public main_frame12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 100, 150));
        jPanel1.setForeground(new java.awt.Color(100, 100, 150));

        jButton7.setText("created date");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("due date");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton5.setText("priority");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton4.setText("alphabetical");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel11.setText("LIST ACCORDING TO");

        jTextField11.setText("jTextField11");

        jLabel12.setText("category name");

        jButton8.setText("list_all_categories");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4)
                        .addComponent(jButton7)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );

        jPanel3.setBackground(new java.awt.Color(55, 78, 150));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton9.setText("clear text area");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel1.setText("category name");

        jTextField1.setText("jTextField1");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("due_date");

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel2.setText("task name");

        jTextField2.setText("jTextField2");

        jLabel6.setText("description");

        jTextField5.setText("jTextField5");

        jLabel3.setText("status");

        jTextField3.setText("jTextField3");

        jLabel7.setText("tags");

        jTextField6.setText("jTextField6");

        jLabel4.setText("priority");

        jTextField7.setText("jTextField7");

        jButton1.setText("add task");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton12.setText("edit task");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(144, 144, 144))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7))
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel3)))))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(189, 189, 189))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12)
                            .addComponent(jButton1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(21, 150, 78));

        jLabel8.setText("category name");

        jTextField8.setText("jTextField8");

        jButton2.setText("submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(200, 0, 0));

        jLabel15.setText("enter word to search");

        jTextField14.setText("jTextField14");

        jButton11.setText("search");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton11)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(200, 177, 0));

        jLabel13.setText("enter search word");

        jTextField12.setText("jTextField12");

        jButton10.setText("search");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel14.setText("enter category name");

        jTextField13.setText("jTextField13");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)))
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(100, 50, 100));

        jLabel9.setText("category");

        jTextField9.setText("jTextField9");

        jLabel10.setText("task_name");

        jTextField10.setText("jTextField10");

        jButton3.setText("delete task");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
            
  
        
        
        
               Boolean m1=(jTextField1.getText().equals(null)||jTextField1.getText().trim().equals(""));
        Boolean m2=(jTextField2.getText().equals(null)||jTextField2.getText().trim().equals(""));
        Boolean m4=(jTextField7.getText().equals(null)||jTextField7.getText().trim().equals(""));
        Boolean m5=(jTextField3.getText().equals(null)||jTextField3.getText().trim().equals(""));
        Boolean m3=(jTextField5.getText().equals(null)||jTextField5.getText().trim().equals(""));
        Boolean m7=  (jTextField6.getText().equals(null)||jTextField6.getText().trim().equals(""));
        Boolean m6=(jTextField4.getText().equals(null)||jTextField4.getText().trim().equals(""));
        if(m1||m2||m3||m4||m5||m6||m7)
        {
            jTextArea1.setText("please enter all fields under task info");
           return;
           
         
            
                    
            
        }
        
        String name_of_category=jTextField1.getText();
                   Boolean	b1=add_task.name_validate(name_of_category);
                  
                  
                   if(b1==false)
                                 {
			        jTextArea1.setText("Boss, enter name containing single word, no spl char, no space, starts with letter...illandre!!");
			        return;
                                
                                
                                 }   
                    Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can create tasks");
                               return;
                            
                             }
                        
                   
                       
                      
                            
                                 
                        
                  
                        

        String task_name=jTextField2.getText();
        Boolean  b4=add_task.name_validate(task_name);
                                
                                
                   
                           if(!b4)
                                 {
			        jTextArea1.setText("Boss, enter name containing single word, no spl char, no space, starts with letter...illandre!!");
			        return;
                                
                                
                                
                                 }
                             Boolean      b5=add_task.is_task_name_unique(task_name,name_of_category);
                             if(b5)
                             {jTextArea1.setText("task name aldready exists, enter different name");
                              return;
                            
                             }
                             
       String tag_string=null;
                             tag_string=jTextField6.getText();
                            if (!add_task.valid_tag(tag_string) || tag_string.equals(null) || tag_string.trim().equals(""))
        {
            jTextArea1.setText("Enter tags which are comma seperated words, eg: imp,fast,done"
                    + " tags should be single word, no spl char, no space, starts with letter"
                    + "");
            return;
                             
        }              
                        
                        
               String description=jTextField5.getText();
               Boolean desc=description.trim().equals("") || description.equals(null)|| description.contains(":");
               if(description.trim().equals("") || description.equals(null)|| description.contains(":"))
                         {
                            jTextArea1.setText("enter description other than null , spaces and it shouldn't contain : !!");
                           return;
                         }
                 String priority=jTextField7.getText();
                  Scanner pr=new Scanner(priority);
                  if(!pr.hasNextInt())
                  {
                      jTextArea1.setText("enter only integers");
                     return;
                  }
                 Integer i=Integer.parseInt(priority);
                 
                 String stat=jTextField3.getText();
                 Boolean f=!(stat.equals("due"))&& !(stat.equals("done"));
                  if(f)
                                 {
                                     jTextArea1.setText("incorrect,enter status: due or done, nothing else acceptable");
                                      return;
                                 }
               
                  
                 String x1= jTextField4.getText().trim();
                 if(x1.length()!=10)
                 {
                     jTextArea1.setText("enter dd/mm/yyyy, only 10 characters");
                     return;
                 }
                  Pattern pattern = 
            Pattern.compile("[0-9]{2}/[0-9]{2}/[0-9]{4}");
               Matcher matcher = 
            pattern.matcher(x1);
               if(!matcher.find())
               {
                   jTextArea1.setText("enter in format dd/mm/yyyy");
                  return;
               }
                if(add_task.validate_date(x1)== false)
                {
                   jTextArea1.setText("Enter date in following format dd-MM-yyyy 0000<years<9999,1<month<12,1<day<31");
                   return;
                }
                
                jTextArea1.setText("good job");
               
                Calendar c= Calendar.getInstance();
                    Date date_created=c.getTime();
                    
                    SimpleDateFormat df=new SimpleDateFormat("dd/mm/yyyy");
             
             
                            
     
            Date  due_date1 = null;
        
        try {
            due_date1 = df.parse(x1);
            
        } catch (ParseException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       
                             
               
                                        
            TaskBean tb=new TaskBean(task_name,description,due_date1,i,stat,tag_string,date_created);
            add_task.Print_task_into_file(name_of_category, tb);
              
                  
    }//GEN-LAST:event_jButton1MouseClicked
    
    
   
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
 String name_of_category=jTextField8.getText();
                   Boolean	b1=add_task.name_validate(name_of_category);
                   Boolean     b2=add_task.is_directory_in_list(name_of_category);
                  
                   if(b1==false)
                                 {
                                  JOptionPane.showMessageDialog(null,"Boss, enter name containing single word, no spl char, no space, starts with letter...illandre!!");
			        jTextArea1.setText("Boss, enter name containing single word, no spl char, no space, starts with letter...illandre!!");
			        return;
                                
                                
                                 }     
                        
                   if(b2==true)
                             {jTextArea1.setText("directory name aldready exists, enter different name");
                               return;
                            
                             }
                        
                   add_task.add_directory_to_list(name_of_category);
                       add_task.create_file_for_directory(name_of_category);
                               // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
 Boolean m1=(jTextField9.getText().equals(null)||jTextField9.getText().trim().equals(""));
        Boolean m2=(jTextField10.getText().equals(null)||jTextField10.getText().trim().equals(""));         
        if(m1 || m2)
        {
            jTextArea1.setText("enter all fields first");
            return;
        }
        
        
        String name_of_category=           jTextField9.getText();
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can delete it");
                               return;
                            
                             }   
                   
         String task_name_to_delete=jTextField10.getText();
         if(!add_task.is_task_name_unique(task_name_to_delete, name_of_category))
         {
              jTextArea1.setText("task name u entered doesn't exist,enter different task name");
              return;
         }
         String p="C:\\Users\\karthik\\Desktop\\"+ name_of_category ;
                                 String f15=  delete_task.recover_entire_line(p,task_name_to_delete );
                                   
                                   delete_task.removeLineFromFile(p, f15);
         
         
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
    Boolean m2=(jTextField11.getText().equals(null)||jTextField11.getText().trim().equals(""));         
        if( m2)
        {
            jTextArea1.setText("enter category name first");
            return;
        }
        String name_of_category=jTextField11.getText();
        
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can list items");
                               return;
                            
                             }      
        
        
        
        
        ArrayList<TaskBean> t = creating_java_bean_list.java_bean_list(name_of_category,1);
                              int y=0;            
                             while(y<t.size()){
                                          jTextArea1.append(t.get(y).outputString());
                                          y++;
                                                  }
                                          
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
 Boolean m2=(jTextField11.getText().equals(null)||jTextField11.getText().trim().equals(""));         
        if( m2)
        {
            jTextArea1.setText("enter category name first");
            return;
        }
        String name_of_category=jTextField11.getText();
        
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can list items");
                               return;
                            
                             }      
        
        
        
        
        ArrayList<TaskBean> t = creating_java_bean_list.java_bean_list(name_of_category,2);
                              int y=0;            
                             while(y<t.size()){
                                          jTextArea1.append(t.get(y).outputString());
                                          y++;
                                                  }
                                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
         Boolean m2=(jTextField11.getText().equals(null)||jTextField11.getText().trim().equals(""));         
        if( m2)
        {
            jTextArea1.setText("enter category name first");
            return;
        }
        String name_of_category=jTextField11.getText();
        
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can list items");
                               return;
                            
                             }      
        
        
        
        
        ArrayList<TaskBean> t = creating_java_bean_list.java_bean_list(name_of_category,3);
                              int y=0;            
                             while(y<t.size()){
                                          jTextArea1.append(t.get(y).outputString());
                                          y++;
                                                  }
                        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        Boolean m2=(jTextField11.getText().equals(null)||jTextField11.getText().trim().equals(""));         
        if( m2)
        {
            jTextArea1.setText("enter category name first");
            return;
        }
        String name_of_category=jTextField11.getText();
        
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can list items");
                               return;
                            
                             }      
        
        
        
        
        ArrayList<TaskBean> t = creating_java_bean_list.java_bean_list(name_of_category,4);
                              int y=0;            
                             while(y<t.size()){
                                          jTextArea1.append(t.get(y).outputString());
                                          y++;
                                                  }
                        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        File f=new File("C:\\Users\\karthik\\Desktop\\directorylist.txt");
        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(f.length()==0)
        {
            jTextArea1.setText("no categories added, please add categories first");
            return;
        }
        
        ArrayList<String> m5=null;
                   try{   m5=list_all_categories.list_all_categories();}
                   catch(IOException p)
                   {
                      p.printStackTrace();
                      
                   }
                     
                     for(int m6=0;m6<m5.size();m6++)
                     {
                         jTextArea1.append(m5.get(m6)+"\n");
                     }
                     
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseExited

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        
        Boolean m2=(jTextField12.getText().equals(null)||jTextField12.getText().trim().equals(""));
        Boolean m3=(jTextField13.getText().equals(null)||jTextField13.getText().trim().equals(""));
        
        
        if(m2||m3)
        {
            jTextArea1.setText("enter both category and search word");
            return;
            
        }
        File f=new File("C:\\Users\\karthik\\Desktop\\directorylist.txt");
        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(f.length()==0)
        {
            jTextArea1.setText("\nno categories added, please add categories first");
            return;
        }
        String name_of_category=jTextField13.getText();
        Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("\nfirst create new directory , then later u can search in it");
                               return;
                            
                             }     
                   String m=jTextField12.getText();
                   if(m.length()==1)
                   {
                       jTextArea1.append("\n search word should have length grater than 1");
                       return;
                   }
                   
        ArrayList<String> h=null;
        try {
            h = RegexTestHarness.RegexTextHarness(name_of_category, m);
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                                 jTextArea1.append("\ntotal "+h.size()+"search results found");
                                 Iterator i=h.iterator();
                                 while(i.hasNext())
                                 jTextArea1.append((String)i.next());
                                  
        
        
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        jTextArea1.setText("");
        Boolean m2=(jTextField14.getText().equals(null)||jTextField14.getText().trim().equals(""));
        
        
        
        if(m2)
        {
            jTextArea1.setText("enter  search word");
            return;
            
        }
        File f=new File("C:\\Users\\karthik\\Desktop\\directorylist.txt");
        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(f.length()==0)
        {
            jTextArea1.setText("\nno categories added, please add categories first");
            return;
        }
          
                   String m=jTextField14.getText();
                   if(m.length()==1)
                   {
                       jTextArea1.append("\n search word should have length grater than 1");
                       return;
                   }
                   
                    ArrayList<list_and_name_bean> d1=null;
        try {
            d1 = search_across_all.search_across_all(m);
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
                     Iterator<list_and_name_bean> hi= d1.iterator();
                   while(  hi.hasNext())
                   {
                      list_and_name_bean f4=hi.next();
                       ArrayList<String> g2=f4.getList();
                       if(g2.size()==0)
                       {
                         jTextArea1.append("no search results sorry"); 
                       }
                       if(g2.size()>0)
                       {
                           jTextArea1.append("\nwe got "+ g2.size()+" results in category. "+f4.getCategory_name()+" They are");
                           Iterator<String> g7=g2.iterator();
                           while(g7.hasNext())
                           {
                               jTextArea1.append(g7.next());
                           }
                       
                           
                   }
                     
                   }
                     
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
           Boolean m1=(jTextField1.getText().equals(null)||jTextField1.getText().trim().equals(""));
        Boolean m2=(jTextField2.getText().equals(null)||jTextField2.getText().trim().equals(""));
        Boolean m4=(jTextField7.getText().equals(null)||jTextField7.getText().trim().equals(""));
        Boolean m5=(jTextField3.getText().equals(null)||jTextField3.getText().trim().equals(""));
        Boolean m3=(jTextField5.getText().equals(null)||jTextField5.getText().trim().equals(""));
        Boolean m7=  (jTextField6.getText().equals(null)||jTextField6.getText().trim().equals(""));
        Boolean m6=(jTextField4.getText().equals(null)||jTextField4.getText().trim().equals(""));
        if(m1||m2||m3||m4||m5||m6||m7)
        {
            jTextArea1.setText("please enter all fields under task info");
           return;
           
        }
            String name_of_category=jTextField1.getText();
          Boolean     b2=add_task.is_directory_in_list(name_of_category);
                        
                   if(b2==false)
                             {jTextArea1.setText("first create new directory , then later u can create tasks");
                               return;
                            
                             }          
             String task_name_to_be_modified=jTextField2.getText();
                                   if(!add_task.is_task_name_unique(task_name_to_be_modified, name_of_category))
                                   {
                                       jTextArea1.setText("task name doesn't exist, enter existing one");
                                       return;
                                   }
                                   String p1="C:\\Users\\karthik\\Desktop\\"+name_of_category;
                                   String tag_string=null;
                             tag_string=jTextField6.getText();
                            if (!add_task.valid_tag(tag_string) || tag_string.equals(null) || tag_string.trim().equals(""))
        {
            jTextArea1.setText("Enter tags which are comma seperated words, eg: imp,fast,done"
                    + " tags should be single word, no spl char, no space, starts with letter"
                    + "");
            return;
                             
        }              
                        
                        
               String description=jTextField5.getText();
               Boolean desc=description.trim().equals("") || description.equals(null)|| description.contains(":");
               if(description.trim().equals("") || description.equals(null)|| description.contains(":"))
                         {
                            jTextArea1.setText("enter description other than null , spaces and it shouldn't contain : !!");
                           return;
                         }
                 String priority=jTextField7.getText();
                  Scanner pr=new Scanner(priority);
                  if(!pr.hasNextInt())
                  {
                      jTextArea1.setText("enter only integers");
                     return;
                  }
                 Integer i=Integer.parseInt(priority);
                 
                 String stat=jTextField3.getText();
                 Boolean f=!(stat.equals("due"))&& !(stat.equals("done"));
                  if(f)
                                 {
                                     jTextArea1.setText("incorrect,enter status: due or done, nothing else acceptable");
                                      return;
                                 }
               
                  
                 String x1= jTextField4.getText().trim();
                 if(x1.length()!=10)
                 {
                     jTextArea1.setText("enter dd/mm/yyyy, only 10 characters");
                     return;
                 }
                  Pattern pattern = 
            Pattern.compile("[0-9]{2}/[0-9]{2}/[0-9]{4}");
               Matcher matcher = 
            pattern.matcher(x1);
               if(!matcher.find())
               {
                   jTextArea1.setText("enter in format dd/mm/yyyy");
                  return;
               }
                if(add_task.validate_date(x1)== false)
                {
                   jTextArea1.setText("Enter date in following format dd-MM-yyyy 0000<years<9999,1<month<12,1<day<31");
                   return;
                }
                
                jTextArea1.setText("good job");
               
                Calendar c= Calendar.getInstance();
                    Date date_created=c.getTime();
                    
                    SimpleDateFormat df=new SimpleDateFormat("dd/mm/yyyy");
             
             
                            
     
            Date  due_date1 = null;
        
        try {
            due_date1 = df.parse(x1);
            
        } catch (ParseException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
                                        
            TaskBean tb=new TaskBean(task_name_to_be_modified,description,due_date1,i,stat,tag_string,date_created);
            add_task.Print_task_into_file(name_of_category, tb);
       
       String s=edit_task.recover_entire_line( p1 ,  task_name_to_be_modified);
                                   
                                   
       edit_task.removeLineFromFile(p1,s);
        
        
    }//GEN-LAST:event_jButton12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     File f=new File("C:\\Users\\karthik\\Desktop\\directorylist.txt");
        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(main_frame12.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
